language: php

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

services:
  - docker

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
 allow_failures:
    - env: DB=pgsql MOODLE_BRANCH=master
    - env: DB=mysqli MOODLE_BRANCH=master
 fast_finish: true


env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - moodle-plugin-ci add-plugin unirz-tu-ilmenau/moodle-tool_opencast
  - git clone https://github.com/opencast/opencast-docker.git /tmp/opencast-docker --depth=1
  - cd /tmp/opencast-docker
  - docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.h2.yml up -d
  - cd -

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.2
#      addons:
#        apt:
#          packages:
#            - oracle-java8-installer
#            - oracle-java8-set-default
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
#      - moodle-plugin-ci phplint
#      - moodle-plugin-ci phpcpd
#      - moodle-plugin-ci phpmd
#      - moodle-plugin-ci codechecker
      - moodle-plugin-ci savepoints
#      - moodle-plugin-ci mustache
#      - moodle-plugin-ci grunt
#      - moodle-plugin-ci validate

    # Smaller build matrix for development builds
    - stage: develop
      php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      before_install:
        - phpenv config-rm xdebug.ini
        - nvm install 8.9.4
        - cd ../..
        - composer selfupdate
        - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
        - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
        - moodle-plugin-ci add-plugin unirz-tu-ilmenau/moodle-tool_opencast
        - git clone https://github.com/opencast/opencast-docker.git /tmp/opencast-docker --depth=1
        - cd /tmp/opencast-docker
        - docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.h2.yml up -d
        - cd -
      install:
      - moodle-plugin-ci install
      script:
      - moodle-plugin-ci phpunit --coverage-clover
      - moodle-plugin-ci behat

# Unit tests and behat tests against full matrix.
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS present)
